FROM python:3.4.6
MAINTAINER Jeehoon Yoo <jihungen@gmail.com>

RUN apt-get update

ADD requirements.txt /var/lightweight-rest-tester/requirements.txt
ADD .coveralls.yml /var/lightweight-rest-tester/.coveralls.yml

WORKDIR /var/lightweight-rest-tester

RUN pip install -r requirements.txt \
    && pip install coveralls[yaml]

ADD . /var/lightweight-rest-tester
