FROM python:3.4.6
MAINTAINER Jeehoon Yoo <jihungen@gmail.com>

RUN apt-get update

ADD requirements.txt /var/lightweight-rest-tester/requirements.txt

WORKDIR /var/lightweight-rest-tester

RUN pip install -r requirements.txt

ADD . /var/lightweight-rest-tester

HEALTHCHECK --interval=5s --timeout=3s CMD curl --fail http://json-server:3000/posts || exit 1
